### ISSUE TITLE
Objective-C files missing

### ISSUE THREAD

**Issue by jtmilne** [GabrielMassana/ButtonBackgroundColor-iOS#3]
Is it my imagination, or have the Objective-C files disappeared from this repo? I'm guessing this was a mistake when adding Swift?

**Comment by GabrielMassana** [comment]
I updated the repo to be Swift now.

Tag 1.1.3 got the Objective-C last code: https://github.com/GabrielMassana/ButtonBackgroundColor-iOS/releases/tag/1.1.3

Since 2.0.0 is Swift.

Sorry for any inconvenience.

**Comment by jtmilne** [comment]
Any reason not to either leave the Objective-C in there or make Swift a separate repo? It seems odd to break the existing repo and essentially kill off a useful tool.

**Comment by GabrielMassana** [comment]
Hi,

The tool was not killed, I just adapted the code to the new language.

You can still install the Objective-C files with:

pod 'ButtonBackgroundColor', '~> 1.0'

Cheers
